## Excel_Challenge_934 - Top Two

### Problem from Excel BI Challenge account on LinkedIn

### Solution author : M R Shaheedullah

In [11]:
# import packages
import openpyxl
import pandas as pd

In [12]:
df = pd.read_excel(r'C:\Users\conif\Documents\Repos\excel-python-challenges\BI-Challenge-934\Excel_Challenge_934.xlsx', sheet_name='data')
df

         Date EmployeeID  ProjectID  Hours
0  2026-03-02        E03    P-Alpha      9
1  2026-03-02        E01    P-Bravo      8
2  2026-03-03        E04    P-Alpha      9
3  2026-03-04        E02    P-Bravo      7
4  2026-03-04        E05    P-Bravo      8
5  2026-03-05        E03    P-Alpha      5
6  2026-03-05        E01    P-Alpha      9
7  2026-03-06        E01    P-Bravo      9
8  2026-03-06        E04    P-Alpha      9
9  2026-03-09        E02    P-Bravo      9
10 2026-03-10        E06    P-Alpha      6
11 2026-03-11        E05  P-Charlie      5
12 2026-03-12        E01    P-Bravo      3
13 2026-03-13        E02    P-Bravo      4
14 2026-03-16        E04    P-Alpha      7
15 2026-03-17        E03    P-Alpha      5
16 2026-03-18        E06    P-Bravo      9
17 2026-03-19        E02    P-Delta      9
18 2026-03-20        E04    P-Alpha      5
19 2026-03-23        E02    P-Delta      9
20 2026-03-24        E02    P-Delta      9
21 2026-03-25        E02    P-Delta      9
22 2026-03-26        E05  P-Charlie      8
23 2026-03-27        E01    P-Alpha      5
24 2026-03-30        E06    P-Bravo      7

In [13]:
df = df.groupby(['EmployeeID','ProjectID'])['Hours'].sum().reset_index()
df.sort_values(by=['ProjectID', 'Hours'], ascending=[True, False], inplace=True)
df['Rank'] = df.groupby('ProjectID')['Hours'].rank('first', ascending=False)
df.sort_values(by=['ProjectID', 'Rank'], inplace=True)
df = df[df['Rank']<3].reset_index()
df = df.groupby(['ProjectID']).agg({'EmployeeID': list}).reset_index()
# delimiter = ','
df['Top 2']=df['EmployeeID'].apply(lambda x : ', '.join(x))
# df['EmployeeID'] = [', '.join(x) for x in df['EmployeeID']]
df.drop(['EmployeeID'], axis=1, inplace=True )
df

   ProjectID     Top 2
0    P-Alpha  E04, E03
1    P-Bravo  E01, E02
2  P-Charlie       E05
3    P-Delta       E02